### ISSUE TITLE
swagger.json generation based on inversify-express-utils annotations? 

### ISSUE THREAD

**Issue by vologab** [w3tecch/express-typescript-boilerplate#3]

**Comment by dweber019** [comment]
@vologab Do you have any experience with your approach?

We had discussed several implementation cases for swagger:
1. Use annotations (Generating swagger automatic)
2. Use doc comments (Generating swagger by comments in implementation files)
3. Use a swagger file (Use a single swagger definition file)

1. Is not flexible enough. As soon as there is something special to do in swagger we have difficulties.
2. The files are huge and you don't see implementation code anymore. I mean you have more swagger code than actual business code ;)
3. It's also not the best solution but at least everything is at one central place and we have one place of failure.

What do you think?

**Comment by vologab** [comment]
@dweber019 I suppose my experience is not relevant, but we can investigate this way - https://github.com/Romakita/ts-express-decorators/pull/74 
Is there ability to extract data  from inversify-express-utils  annotations, without parsing them as text, but with small runtime impact and without inversify-express-utils modification?

**Comment by dweber019** [comment]
@vologab In almost any project we worked with the one single file solution because as soon as our projects reached a sertain complexity we had issues with the generators and had to switch back.

In addition we are using this project (https://www.npmjs.com/package/swagger-server) to mock our API.

But if you have any suggestions or you like to do a PR, I'm happy to check it.
